import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// Inhein import karein
import ReduxProvider from "@/redux/provider"; 
import AuthWrapper from "@/components/AuthWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Crayon-Coasting App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Sabse pehle Redux Provider, phir AuthWrapper */}
        <ReduxProvider>
          <AuthWrapper>
            {children}
          </AuthWrapper>
        </ReduxProvider>
      </body>
    </html>
  );
}